name: CEKLIS

on: [push]

env:
  MAVEN_ARGS: >-
    -Dmaven.javadoc.skip=true
    -B -V --no-transfer-progress
    -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
jobs:
  postgres-1:
    name: buil-1
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        postgres: [9, 10, 11, 12]
        flag: [aa, bb, cc, dd, ee, ff, gg, hh, II, jj]
    services:
      postgres:
        image: postgres:${{ matrix.postgres }}
        env:
          POSTGRES_PASSWORD: flowable
          POSTGRES_USER: flowable
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a health check
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5 --tmpfs /var/lib/postgresql/data:rw
    steps:
      - uses: actions/checkout@v2
      - name: Test
        # use postgres for the host here because we have specified a container for the job.
        # If we were running the job on the VM this would be localhost
        # '>-' is a special YAML syntax and means that new lines would be replaced with spaces
        # and new lines from the end would be removed
        run: |
         echo "1"
